name: "sokol-shared"

on:
  push:
    branches:
      - '*'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 12.x
        uses: actions/setup-node@v4
        with:
          node-version: 12.x
      - name: npm install and test
        run: |
          npm install --production
        env:
          CI: true