name: "build-wasm2lua"

on:
  push:
    branches:
      - '*'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 12.x
        uses: actions/setup-node@v4
        with:
          node-version: 12.x
      - name: npm install and test
        run: |
          mkdir -p ./install/wasm2lua/node_modules
          npm install --prefix ./install/wasm2lua wasm2lua
          mkdir -p ./install/webidl/node_modules
          npm install --prefix ./install/web-idl web-idl
        env:
          CI: true

      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: Linux node app
          path: |
            ./install/wasm2lua