name: "build-wasm2lua"

on:
  push:
    branches:
      - '*'

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 12.x
        uses: actions/setup-node@v4
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install -g pkg
        env:
          CI: true
      - name: npm package
        run: |
          pkg --out-path ./bin .
        env:
          CI: true
      - name: Archive results
        uses: actions/upload-artifact@v4
        with:
          name: Multi Platform Builds
          path: |
            ./bin
